---
image: jdubz/ci-docker-ansible:latest

services:
  - docker:19.03.1-dind

molecule:
  stage: test
  script:
    - ansible --version
    - molecule converge -s custom -- -vvv
    - molecule converge -s default -- -vvv
    - molecule test --all
