---
image: jdubz/ci-docker-ansible:latest

services:
  - docker:19.03.1-dind

molecule:
  stage: test
  before_script:
    - pip install jmespath
    - ansible --version
  script:
    - molecule test --all
