---
- name: generate a zone serial
  command: "date +%Y%m%d01"
  register: dubzland_bind9_default_serial
  changed_when: False

- name: ensure bind9 key files exist
  template:
    src: "etc/bind/key.j2"
    dest: "/etc/bind/{{ key.name }}.key"
    owner: root
    group: bind
    mode: 0660
  loop: "{{ dubzland_bind9_keys }}"
  loop_control:
    loop_var: key
    label: "{{ key.name }}"
  notify:
    - restart bind9
  tags:
    - bind9
    - dns

- name: ensure the zone file directory is present
  file:
    path: "{{ dubzland_bind9_zone_directory }}"
    state: directory
    owner: root
    group: bind
    mode: 0775
  tags:
    - bind9
    - dns

- name: ensure the view directories are present
  file:
    path: "{{ '%s/%s' | format(dubzland_bind9_zone_directory, item.name) }}"
    state: directory
    owner: root
    group: bind
    mode: 0775
  loop: "{{ dubzland_bind9_views }}"
  loop_control:
    label: "{{ '%s/%s' | format(dubzland_bind9_zone_directory, item.name) }}"
  when: dubzland_bind9_views | length > 0
  tags:
    - bind9
    - dns

- name: ensure Bind9 is configured
  template:
    src: "etc/bind/{{ item }}.j2"
    dest: "/etc/bind/{{ item }}"
    owner: root
    group: bind
    mode: 0660
  with_items:
    - named.conf
    - named.conf.options
    - named.conf.local
  notify:
    - restart bind9
  tags:
    - bind9
    - dns
