---
- name: generate a zone serial
  command: "date +%Y%m%d01"
  register: dubzland_bind9_default_serial
  changed_when: False

- name: ensure bind9 key files exist
  template:
    src: "etc/bind/key.j2"
    dest: "/etc/bind/{{ key.name }}.key"
    owner: root
    group: bind
    mode: 0660
  loop: "{{ dubzland_bind9_keys }}"
  loop_control:
    loop_var: key
    label: "{{ key.name }}"
  notify:
    - restart bind9
  tags:
    - bind9
    - dns

- name: ensure the zone file directory is present
  file:
    path: "{{ dubzland_bind9_zone_directory }}"
    state: directory
    owner: root
    group: bind
    mode: 0775
  tags:
    - bind9
    - dns

- name: ensure the view directories are present
  file:
    path: "{{ '%s/%s' | format(dubzland_bind9_zone_directory, item.name) }}"
    state: directory
    owner: bind
    group: bind
    mode: 0775
  loop: "{{ dubzland_bind9_views }}"
  loop_control:
    label: "{{ '%s/%s' | format(dubzland_bind9_zone_directory, item.name) }}"
  when: dubzland_bind9_views | length > 0
  tags:
    - bind9
    - dns

- name: ensure Bind9 is configured
  template:
    src: "etc/bind/{{ item }}.j2"
    dest: "/etc/bind/{{ item }}"
    owner: root
    group: bind
    mode: 0660
  with_items:
    - named.conf
    - named.conf.options
    - named.conf.local
  notify:
    - restart bind9
  tags:
    - bind9
    - dns

- name: ensure view based zone files exist
  bind9_zone:
    name: "{{ item.1.name }}"
    admin: "{{ item.1.admin | default('hostmaster') }}"
    nameservers: "{{ item.1.nameservers | default([]) }}"
    mailservers: "{{ item.1.mailservers | default([]) }}"
    records: "{{ item.1.records | default([]) }}"
    view: "{{ item.0.name }}"
    zone_directory: "{{ dubzland_bind9_zone_directory }}"
    dynamic: "{{ item.1.dynamic | default(False) }}"
  loop: "{{ dubzland_bind9_views | subelements('zones') }}"
  loop_control:
    label: "{{ item.0.name }}/{{ item.1.name }}"
  when:
    - (dubzland_bind9_views | default([])) | length > 0
    - item.1.type == 'master'
  notify:
    - reload bind9

- name: ensure normal zone files exist
  bind9_zone:
    name: "{{ zone.name }}"
    admin: "{{ zone.admin | default('hostmaster') }}"
    nameservers: "{{ zone.nameservers | default([]) }}"
    mailservers: "{{ zone.mailservers | default([]) }}"
    records: "{{ zone.records | default([]) }}"
    zone_directory: "{{ dubzland_bind9_zone_directory }}"
    dynamic: "{{ zone.dynamic | default(False) }}"
  loop: "{{ dubzland_bind9_zones }}"
  loop_control:
    label: "{{ zone.name }}"
    loop_var: "zone"
  when:
    - (dubzland_bind9_zones | default([])) | length > 0
    - zone.type == 'master'
  notify:
    - reload bind9
