---
- name: build the list of DDNS updates
  set_fact:
    dubzland_bind9_ddns_updates: "{{ lookup('template', 'lookups/_ddns_updates.j2', convert_data=False) | from_yaml }}"

- name: dump the list of ddns updates
  debug:
    var: dubzland_bind9_ddns_updates

- name: ensure all specified host entries are present
  nsupdate:
    key_name: "{{ dubzland_bind9_nsupdate_key.name }}"
    key_algorithm: "{{ dubzland_bind9_nsupdate_key.algorithm }}"
    key_secret: "{{ dubzland_bind9_nsupdate_key.secret }}"
    server: 127.0.0.1
    zone: "{{ record.zone }}"
    record: "{{ record.record }}"
    value: "{{ record.value }}"
    type: "{{ record.type }}"
    state: "{{ record.state }}"
  loop: "{{ dubzland_bind9_ddns_updates }}"
  loop_control:
    loop_var: record
  tags:
    - bind9
    - dns
