---
- name: build the list of DDNS updates
  set_fact:
    dubzland_bind9_ddns_updates: "{{ lookup('template', 'lookups/_ddns_updates.j2', convert_data=False) | from_yaml }}"

- name: ensure all specified host entries are present
  nsupdate:
    key_name: "{{ record.key.name }}"
    key_algorithm: "{{ record.key.algorithm }}"
    key_secret: "{{ record.key.secret }}"
    server: 127.0.0.1
    zone: "{{ record.zone }}"
    record: "{{ record.record }}"
    value: "{{ record.value }}"
    type: "{{ record.type }}"
    state: "{{ record.state }}"
  loop: "{{ dubzland_bind9_ddns_updates }}"
  loop_control:
    loop_var: record
    label: "zone: {{ record.zone }}, type: {{ record.type }}, record: {{ record.record }}, value: {{ record.value }}, state: {{ record.state }}"
  tags:
    - bind9
    - dns
