---
- include_tasks: variables.yml
- include_tasks: packages.yml
- include_tasks: configuration.yml

- meta: flush_handlers

- include_tasks: hosts.yml

- name: ensure bind9 is running
  service:
    name: bind9
    state: started
