---
- name: grab any existing zone details
  bind_zone_details:
    zone_directory: "{{ dubzland_bind9_zone_directory }}"

- name: dump the zone details
  debug:
    var: bind_zone_details

- name: generate the static zone list
  set_fact:
    dubzland_bind9_static_zones: "{{ lookup('template', 'lookups/_static_zones.j2', convert_data=False) | from_yaml }}"
  tags:
    - bind9
    - dns

- name: dump the static zone list
  debug:
    var: dubzland_bind9_static_zones

- name: ensure the static zone files are present
  template:
    src: var/cache/bind/zone.j2
    dest: "{{ zone.file }}"
    owner: root
    group: bind
    mode: 0660
  loop: "{{ dubzland_bind9_static_zones }}"
  loop_control:
    loop_var: zone
    label: "{{ zone.file }}"
  notify: restart bind9
  tags:
    - bind9
    - dns
